

simulations: config/simulations.tsv
analyses: config/analyses.tsv

PATHS:
    SLiM: /usr/bin/slim
    rfmix: /path/to/file
    rfmix2: /path/to/file
    ELAI: /path/to/file
    MOSAIC: /path/to/file
    


DEMOGRAPHIC_MODELS:
  american_admixture:
    organism: human
    file: /path/to/file
    # could put separate config files here
  ooa_4pop:
    organism: human
    file: /path/to/file
  simple_admixture:
    organism: human
    file: /path/to/file
