simulations: config/simulations.tsv
analyses: config/analyses.tsv

# put full paths in here, dont use '~' for your home directory (not sure why)
PATHS:
    SLiM: /usr/bin/slim
    BCFTOOLS: /home/kele/programs/bcftools/bcftools-1.11/bcftools
    BEAGLE: programs/BEAGLE/beagle.28Jun21.220.jar
    RFMix: programs/RFmix/RFMix_v1.5.4/RunRFMix.py
    RFMix2: programs/RFmix2/rfmix
    MOSAIC: programs/MOSAIC/MOSAIC/mosaic.R
    BMIX: programs/bmix/bmix.v42.jar
    ADD_ERR: programs/add_err/add-err.jar
    ELAI: /path/to/file

diagnostic_plots: True

DEMOGRAPHIC_MODELS:
  american_admixture:
    organism: human
    file: /path/to/file
    # could put separate config files here
  ooa_4pop:
    organism: human
    file: /path/to/file
  simple_admixture:
    organism: human
    file: /path/to/file
