
simulations: config/simulations.tsv
analyses: config/analyses.tsv

# put full paths in here, dont use '~' for your home directory, not sure why
PATHS:
    SLiM: /usr/bin/slim
    BCFTOOLS: /home/kele/programs/bcftools/bcftools-1.11/bcftools
    RFMix: programs/RFmix/RFMix_v1.5.4/RunRFMix.py
    RFMix2: programs/RFmix2/rfmix
    ELAI: /path/to/file
    MOSAIC: /path/to/file

diagnostic_plots: True

DEMOGRAPHIC_MODELS:
  american_admixture:
    organism: human
    file: /path/to/file
    # could put separate config files here
  ooa_4pop:
    organism: human
    file: /path/to/file
  simple_admixture:
    organism: human
    file: /path/to/file
