channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python
  - snakemake
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - msprime
  - tskit
  - stdpopsim>=0.1.2
  - tszip
  - pytables
  - jupyter
  - notebook
  - openjdk
  - pip
  - xarray
  - scikit-allel
  - numba
  - pip:
    - pyreadr
  - r-base
  - r-essentials
  - r-Rcpp
  - r-ff
  - r-combinat
  - r-LaF
  - r-argparser
  - r-doParallel
  - r-reticulate
