channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - python
  - snakemake
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - msprime
  - tskit
  - stdpopsim
  - tszip
  - pytables
  - jupyter
  - notebook
  - openjdk
  - r-base=3.6.3
  - r-essentials
  - r-Rcpp
  - r-ff
  - r-combinat
  - r-LaF
  - r-argparser
  - r-doParallel
