simulations: config/revision.simulations.tsv
ascertainments: config/revision.ascertainments.tsv
analyses: config/revision.analyses.tsv

# put full or relative paths in here
# dont use '~' for your home directory (not sure why)
PATHS:
    SLiM: programs/SLiM/slim
    BCFTOOLS: programs/bcftools-1.16/bcftools
    BEAGLE: programs/BEAGLE/beagle.22Jul22.46e.jar
    RFMix: programs/RFmix/RFMix_v1.5.4/RunRFMix.py
    RFMix2: programs/RFmix2/rfmix/rfmix
    MOSAIC: programs/MOSAIC/mosaic/mosaic.R
    FLARE: programs/flare/flare.v0.3.0.jar
    ADD_ERR: programs/add_err/add-err.jar
