simulations: config/revision.simulations.tsv
ascertainments: config/revision.ascertainments.tsv
analyses: config/revision.analyses.tsv

cpus: 20
email: "ryan.waples@gmail.com"
email_type: "FAIL"

# put full paths in here
# dont use '~' for your home directory (not really sure why)
PATHS:
    SLiM: programs/SLiM/slim
    BCFTOOLS: /home/users/waplesr/lai/lai-sim/programs/bcftools-1.14/bcftools
    BEAGLE: programs/BEAGLE/beagle.28Jun21.220.jar
    RFMix: programs/RFmix/RFMix_v1.5.4/RunRFMix.py
    RFMix2: programs/RFmix2/rfmix/rfmix
    MOSAIC: programs/MOSAIC/mosaic/mosaic.R
    FLARE: programs/flare/flare.v13.jar
    ADD_ERR: programs/add_err/add-err.jar
