simulations: config/personal.simulations.tsv
ascertainments: config/personal.ascertainments.tsv
analyses: config/personal.analyses.tsv

# put full paths in here, dont use '~' for your home directory (not sure why)
PATHS:
    SLiM: /home/kele/Documents/lai/lai-sim/programs/SLiM/slim
    BCFTOOLS: /home/kele/Documents/lai/lai-sim/programs/bcftools/bcftools-1.14/bcftools
    BEAGLE: programs/BEAGLE/beagle.28Jun21.220.jar
    RFMix: programs/RFmix/RFMix_v1.5.4/RunRFMix.py
    RFMix2: programs/RFmix2/rfmix/rfmix
    MOSAIC: programs/MOSAIC/mosaic/mosaic.R
    BMIX: programs/bmix/bmix.jar
    ADD_ERR: programs/add_err/add-err.jar
    ELAI: /path/to/file

diagnostic_plots: True

DEMOGRAPHIC_MODELS:
  american_admixture:
    organism: human
    file: /path/to/file
  ooa_4pop:
    organism: human
    file: /path/to/file
  simple_admixture:
    organism: human
    file: /path/to/file
